config/routes.rb
Rails.application.routes.draw do
  get     '/login',     to: 'sessions#new',        as: 'new_login'
  post    '/login',     to: 'sessions#create',     as: 'login'
  delete  '/logout',    to: 'sessions#destroy',    as: 'logout'

  resources :links
  resources :users

  post '/voteup/:link_id', to: 'votes#vote_up', as: 'vote_up'
  post '/votedown/:link_id', to: 'votes#vote_down', as: 'vote_down'

  root "links#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  validates :url, length: { minimum: 8, message: "Must be at least 8 characters" }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order(num_votes: :desc).order(updated_at: :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    authenticate_user
    @link = Link.new
  end

  # GET /links/1/edit
  def edit

  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    if @link.user_id != current_user.id
      redirect_to :back, alert: "You are not AUTHORIZED to delete this link."
    else
      @link.destroy
      respond_to do |format|
        format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url, :user_id, :num_votes)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link, class: "btn btn-danger" %>
<%= link_to 'Back', links_path, class: "btn btn-success" %>

app/views/links/index.html.erb
<h1>Iron Reddit Links</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Url</th>
      <th>User</th>
      <th>Votes</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.url %></td>
        <td><%= link.user.name %></td>
        <td class="bigger"><%= link.num_votes %><%= link_to('Vote Up', vote_up_path(link), method: :post, class: "btn btn-info space space-left") %><%= link_to('Vote Down', vote_down_path(link), method: :post, class: "btn btn-warning space") %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) unless @current_user == nil || @current_user.id != link.user_id %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } unless @current_user == nil || @current_user.id != link.user_id %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

<br>
<%= link_to 'Highlight Most Popular Link', '#', class: "btn btn-warning", id: "highlight" %>
<%= link_to 'New Link', new_link_path, class: "btn btn-info" %>
<%= link_to 'Login', login_path, class: "btn btn-default" if !user_logged_in? %>
<p> Don't have an account yet? Click <%= link_to 'here', new_user_path %> to sign up!</p>

app/views/links/new.html.erb
<h1>New Link</h1>
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2> Error(s) prohibited this link from being saved:</h2>
      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component('NewLinkForm') %>

  <%= f.submit "Publish Post", class: "btn btn-info" %>
<% end %>
<br/>

app/views/links/show.html.erb
<h4>
  <strong>Url: </strong><%= @link.url %>
</h4>

<p>
  <strong>Num votes:</strong>
  <%= @link.num_votes %>
</p>

<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-success" unless @current_user == nil || @current_user.id != @link.user_id %>
<%= link_to 'Back', links_path, class: "btn btn-primary" %>